# properties for local development setup
server.port=8080
# "mem" signifies that the database (named taskdb) exists in memory 
spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1 
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=your-super-secret-jwt-key-that-should-be-at-least-256-bits-long-for-security
app.jwt.expiration-ms=86400000

# Your LLM API key (set this as an environment variable when deploying, we used Groq key for our own testing)
app.ai.api-key=${AI_API_KEY:demo-key}