# properties for deployement base
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Disable H2 in production
spring.h2.console.enabled=false

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# AI
app.ai.api-key=${AI_API_KEY}